kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-pv
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  awsElasticBlockStore:
    volumeID: vol-0885d806ab42e2146
    fsType: ext4
